baseURL = 'https://www.montenegro.com.br/'
theme = "hugo-coder"
defaultcontentlanguage = "pt"
languageCode = 'pt'
title = 'Leonardo Gon√ßalves Montenegro, BSc.'


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Leonardo Montenegro"
  info = "My Happy Sad Life"
  description = "Let's talk about..."
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpeg"
  
  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"